// Writes contract ABIs, known deployments and the card catalog into the app as TypeScript.
const fs = require("fs");
const path = require("path");
const config = require("../config/robinhood.json");

const ARTIFACTS = path.join(__dirname, "..", "artifacts", "src");
const OUT_DIR = path.join(__dirname, "..", "..", "app", "src", "generated");
const CONTRACTS = { oddsRoundsAbi: "OddsRounds.sol/OddsRounds.json", oddsBurnAbi: "OddsBurn.sol/OddsBurn.json" };

fs.mkdirSync(OUT_DIR, { recursive: true });
let abis = "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n";
for (const [name, file] of Object.entries(CONTRACTS)) {
  const { abi } = JSON.parse(fs.readFileSync(path.join(ARTIFACTS, file), "utf8"));
  abis += `export const ${name} = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
}
fs.writeFileSync(path.join(OUT_DIR, "abis.ts"), abis);

const deployments = {};
const dir = path.join(__dirname, "..", "deployments");
if (fs.existsSync(dir)) {
  for (const f of fs.readdirSync(dir).filter((f) => f === "robinhood.json" || f === "localhost.json")) {
    const d = JSON.parse(fs.readFileSync(path.join(dir, f), "utf8"));
    deployments[d.chainId] = d;
  }
}
fs.writeFileSync(
  path.join(OUT_DIR, "deployments.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" +
    `export const deployments: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};\n\n` +
    `type A = \`0x\${string}\`;
export type Deployment = {
  network: string;
  chainId: number;
  deployer: A;
  roles: { admin: A; guardian: A; keeper: A };
  timelock: A;
  rounds: A;
  burn: A;
  usdg: A;
  oddsToken: A | null;
  assets: Record<string, { token: A; pool: A; fee: number; observations: number; price?: number }>;
  [key: string]: unknown;
};\n`
);

const catalog = {
  chainId: config.network.chainId,
  explorer: config.network.explorer,
  pons: config.pons,
  assets: config.odds.assets,
  cards: config.odds.cards,
  weekdayHours: config.odds.weekdayHours,
  feeBps: config.odds.feeBps,
  minStake: config.odds.minStake,
  maxStake: config.odds.maxStake,
  roundCap: config.odds.roundCap,
};
fs.writeFileSync(
  path.join(OUT_DIR, "catalog.ts"),
  "// Generated by contracts/scripts/export-abis.js. Do not edit.\n\n" + `export const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`
);
console.log(`Exported ${Object.keys(CONTRACTS).length} ABIs and ${Object.keys(deployments).length} deployment(s) to ${OUT_DIR}`);
